# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bt < Formula
  desc "gh-style CLI for Bitbucket Cloud and Data Center"
  homepage "https://github.com/arogan178/bitbucket-cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arogan178/bitbucket-cli/releases/download/v0.1.1/bt_0.1.1_darwin_amd64.tar.gz"
      sha256 "6c04431274edc4a9f687ac6d62cfee1c8add2161cd26ff3f7e9d2e3ec471f5ab"

      define_method(:install) do
        bin.install "bt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arogan178/bitbucket-cli/releases/download/v0.1.1/bt_0.1.1_darwin_arm64.tar.gz"
      sha256 "efef55d2055524f9bab27a5f627b66f46433e98106ad93992f848be0526a5779"

      define_method(:install) do
        bin.install "bt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arogan178/bitbucket-cli/releases/download/v0.1.1/bt_0.1.1_linux_amd64.tar.gz"
      sha256 "463b9e78e8bf6121106927945c47d3599df57517446cc37a89601e15b391127c"
      define_method(:install) do
        bin.install "bt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arogan178/bitbucket-cli/releases/download/v0.1.1/bt_0.1.1_linux_arm64.tar.gz"
      sha256 "d73d516534535b965e101c64f680df351c75af9a1085abfb7a5e7aae507354b9"
      define_method(:install) do
        bin.install "bt"
      end
    end
  end

  test do
    system "#{bin}/bt --version"
  end
end
