# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bt < Formula
  desc "gh-style CLI for Bitbucket Cloud and Data Center"
  homepage "https://github.com/arogan178/bitbucket-cli"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/arogan178/bitbucket-cli/releases/download/v0.1.2/bt_0.1.2_darwin_amd64.tar.gz"
      sha256 "fc5b16894ae483f55474e20353eed1235ff61f6c4c9349a6a61f1890a9b8b8c7"

      define_method(:install) do
        bin.install "bt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/arogan178/bitbucket-cli/releases/download/v0.1.2/bt_0.1.2_darwin_arm64.tar.gz"
      sha256 "47b90a6bfcdbba223622fe4cbc0588327ecdd879851c0345155f1c14e58aa675"

      define_method(:install) do
        bin.install "bt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/arogan178/bitbucket-cli/releases/download/v0.1.2/bt_0.1.2_linux_amd64.tar.gz"
      sha256 "775665ee6fbd5849891e271d3349a1e4d9f3ba99809561926d48e0a9f17212b4"
      define_method(:install) do
        bin.install "bt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/arogan178/bitbucket-cli/releases/download/v0.1.2/bt_0.1.2_linux_arm64.tar.gz"
      sha256 "81be7b8aa2f6d141c8918e94fc477ffe328bdd5ada34e90bf4af0cf5b71dc2af"
      define_method(:install) do
        bin.install "bt"
      end
    end
  end

  test do
    system "#{bin}/bt --version"
  end
end
